# Generated by Django 3.2.5 on 2022-02-28 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'verbose_name_plural': 'Chat Histories'},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
